# 各手順書の目次更新
name: Update Markown TOC

# トリガーイベントの指定
on:
  push:
    paths: 
      - '**.md'

  # ブラウザ上からの手動実行設定
  workflow_dispatch:

# 実行する処理
jobs:
  UpdateTOC:
    name: UpdateToc
    runs-on: ubuntu-20.04
    steps:
      - name: TOC Generator
        uses: technote-space/toc-generator@v3
        with:
          # 目次を更新するファイル
          TARGET_PATHS: doc/FOR_MAINTAINER.md
          # 目次を作成する最大階層レベル
          MAX_HEADER_LEVEL: 3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 目次の見出し
          TOC_TITLE: '**目次**'
